In [110]:
import pandas as pd
import numpy as np

dataset=pd.read_csv('cardio_dataset.csv').values

data=dataset[:,0:7]
target=dataset[:,7]

target=np.reshape(target, (-1,1))

print(data[:10])
print(target[:10])
print('size of the dataset:',len(dataset))

[[  1.  48. 236.  66.   0.   1.   0.]
 [  0.  48. 260.  51.   0.   1.   1.]
 [  0.  44. 187.  49.   1.   1.   0.]
 [  1.  42. 216.  57.   1.   1.   0.]
 [  1.  56. 156.  42.   0.   1.   0.]
 [  0.  44. 162.  57.   1.   1.   0.]
 [  0.  50. 244.  47.   0.   1.   0.]
 [  0.  48. 212.  30.   1.   1.   0.]
 [  1.  66. 202.  53.   0.   1.   1.]
 [  0.  63. 186.  46.   1.   1.   0.]]
[[ 1.1]
 [ 7. ]
 [ 7. ]
 [ 0.4]
 [ 2.2]
 [ 3. ]
 [ 4.2]
 [17.4]
 [13.4]
 [17.3]]
size of the dataset: 6644


In [111]:
from sklearn.model_selection import train_test_split

train_data,test_data,train_target,test_target=train_test_split(data,target,test_size=0.1)

In [112]:
from sklearn.linear_model import LinearRegression

model=LinearRegression()

model.fit(train_data,train_target)
predicted_target=model.predict(test_data)

In [113]:
from sklearn.metrics import r2_score

r2=r2_score(test_target,predicted_target)
print("r2 score:",r2)

r2 score: 0.7604436698660202


In [114]:
print('Actual :',test_target[:10].T)
print('Predic :',np.round(predicted_target[:10].T))

Actual : [[ 9.5  6.1 23.2  0.2 12.7  2.4 12.  12.8 11.   2.6]]
Predic : [[19.  6. 24. -6. 16.  4. 16. 18. 15.  7.]]


In [115]:
import joblib

joblib.dump(model,'heart_risk_prediction_regression_model.sav')

['heart_risk_prediction_regression_model.sav']